-- Per-hospital workspace configuration surfaced by the UI's Settings module.

CREATE TABLE workspace_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id   BIGINT        NOT NULL,
    setting_key   VARCHAR(100)  NOT NULL,
    setting_value VARCHAR(1000) NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_workspace_settings UNIQUE (hospital_id, setting_key),
    CONSTRAINT fk_workspace_settings_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id)
);
