-- =====================================================================================
-- Laboratory queue. Not part of the reference ERD (it covers phase-1 clinical core), so
-- it follows the same tenancy rules while keeping MedFlow's own uppercase status values.
-- =====================================================================================

CREATE TABLE lab_orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id    BIGINT       NOT NULL,
    patient_id     BIGINT       NOT NULL,
    doctor_id      BIGINT       NOT NULL,
    test_name      VARCHAR(150) NOT NULL,
    priority       VARCHAR(20)  NOT NULL DEFAULT 'ROUTINE',
    status         VARCHAR(20)  NOT NULL DEFAULT 'ORDERED',
    result_summary VARCHAR(2000),
    ordered_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at   TIMESTAMP WITH TIME ZONE,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_lab_orders_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_lab_orders_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_lab_orders_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT ck_lab_orders_priority CHECK (priority IN ('ROUTINE', 'URGENT', 'STAT')),
    CONSTRAINT ck_lab_orders_status CHECK (status IN ('ORDERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_lab_orders_patient ON lab_orders (patient_id);
CREATE INDEX idx_lab_orders_hospital_status ON lab_orders (hospital_id, status);
