-- =====================================================================================
-- Scheduling. queue_number is assigned per doctor per day so walk-in patients can be
-- called in order; consultation_fee is snapshotted at booking time so later fee changes
-- never rewrite revenue history (reason and consultation_fee extend the reference design).
-- =====================================================================================

CREATE TABLE appointments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id        BIGINT      NOT NULL,
    doctor_id          BIGINT      NOT NULL,
    patient_id         BIGINT      NOT NULL,
    appointment_mode   VARCHAR(20) NOT NULL DEFAULT 'online',
    scheduled_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes   INTEGER     NOT NULL DEFAULT 30,
    status             VARCHAR(30) NOT NULL DEFAULT 'booked',
    queue_number       INTEGER,
    booked_by_user_id  BIGINT,
    reason             VARCHAR(255),
    consultation_fee   NUMERIC(10, 2) NOT NULL DEFAULT 0,
    notes              VARCHAR(1000),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_appointments_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_appointments_booked_by FOREIGN KEY (booked_by_user_id) REFERENCES users (id),
    CONSTRAINT ck_appointments_mode CHECK (appointment_mode IN ('online', 'walk_in')),
    CONSTRAINT ck_appointments_status CHECK (status IN ('booked', 'confirmed', 'checked_in', 'in_consultation', 'completed', 'cancelled', 'no_show'))
);

CREATE INDEX idx_appointments_doctor_time ON appointments (doctor_id, scheduled_at);
CREATE INDEX idx_appointments_patient ON appointments (patient_id);
CREATE INDEX idx_appointments_hospital_time ON appointments (hospital_id, scheduled_at);
CREATE INDEX idx_appointments_status ON appointments (status);
