-- =====================================================================================
-- Prescriptions. Medication lines are stored as a JSON document (medicines_json) rather
-- than as rows: a prescription is a signed clinical record and must read back exactly as
-- it was written, even if the pharmacy catalogue is later renamed or pruned.
-- status / updated_at extend the reference design with the UI's lifecycle actions.
-- =====================================================================================

CREATE TABLE prescriptions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id      BIGINT      NOT NULL,
    appointment_id   BIGINT,
    doctor_id        BIGINT      NOT NULL,
    patient_id       BIGINT      NOT NULL,
    diagnosis        VARCHAR(2000),
    medicines_json   VARCHAR(8000) NOT NULL,
    digitally_signed BOOLEAN     NOT NULL DEFAULT FALSE,
    signed_at        TIMESTAMP WITH TIME ZONE,
    status           VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_prescriptions_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_prescriptions_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id),
    CONSTRAINT fk_prescriptions_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT ck_prescriptions_status CHECK (status IN ('active', 'completed', 'cancelled'))
);

CREATE INDEX idx_prescriptions_patient ON prescriptions (patient_id);
CREATE INDEX idx_prescriptions_doctor ON prescriptions (doctor_id);
CREATE INDEX idx_prescriptions_hospital ON prescriptions (hospital_id);
