-- =====================================================================================
-- MedFlow AI — platform core: tenants (hospitals) and the licensable module catalogue.
--
-- Schema follows the ArchitechDB design:
--   * BIGINT / INTEGER identity primary keys
--   * every tenant-owned row carries hospital_id
--   * enum-typed columns are VARCHAR + CHECK constraints holding the exact enum values
--     from the design (portable across PostgreSQL and the in-memory test database)
--   * instants are TIMESTAMP WITH TIME ZONE so multi-timezone hospitals stay correct
-- =====================================================================================

CREATE TABLE hospitals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_code   VARCHAR(20)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    legal_name      VARCHAR(200),
    hospital_type   VARCHAR(50),
    address_line1   VARCHAR(200),
    address_line2   VARCHAR(200),
    city            VARCHAR(100),
    state           VARCHAR(100),
    country         VARCHAR(100),
    pincode         VARCHAR(10),
    phone           VARCHAR(20),
    email           VARCHAR(120),
    timezone        VARCHAR(50)  NOT NULL DEFAULT 'Asia/Kolkata',
    status          VARCHAR(30)  NOT NULL DEFAULT 'active',
    onboarded_at    TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    is_deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_hospitals_code UNIQUE (hospital_code),
    CONSTRAINT ck_hospitals_status CHECK (status IN ('active', 'inactive', 'suspended', 'pending_verification'))
);

-- Catalogue of product modules (phase 1 ships doctors → settings; later phases are
-- listed but not entitled). Mirrors the MedFlow UI navigation one-to-one.
CREATE TABLE modules_master (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code  VARCHAR(50)  NOT NULL,
    module_name  VARCHAR(100) NOT NULL,
    phase        INTEGER      NOT NULL DEFAULT 1,
    description  VARCHAR(500),
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_modules_master_code UNIQUE (module_code)
);

-- Which modules a hospital may use, and until when.
CREATE TABLE hospital_module_entitlements (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id  BIGINT      NOT NULL,
    module_id    INTEGER     NOT NULL,
    status       VARCHAR(30) NOT NULL DEFAULT 'active',
    activated_at TIMESTAMP WITH TIME ZONE,
    expires_at   TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_entitlements_hospital_module UNIQUE (hospital_id, module_id),
    CONSTRAINT fk_entitlements_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_entitlements_module FOREIGN KEY (module_id) REFERENCES modules_master (id),
    CONSTRAINT ck_entitlements_status CHECK (status IN ('trial', 'active', 'expired', 'disabled'))
);

CREATE INDEX idx_entitlements_hospital ON hospital_module_entitlements (hospital_id);
