-- =====================================================================================
-- Role based access control: roles, fine-grained permissions and portal (module) access
-- granted to a user group. Roles and permissions are platform-wide; role_permissions may
-- be overridden per hospital (hospital_id NULL = platform default grant).
-- =====================================================================================

CREATE TABLE roles (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code      VARCHAR(50)  NOT NULL,
    role_name      VARCHAR(100) NOT NULL,
    description    VARCHAR(500),
    is_system_role BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_roles_code UNIQUE (role_code)
);

CREATE TABLE permissions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL,
    module_id       INTEGER,
    permission_name VARCHAR(150) NOT NULL,
    description     VARCHAR(500),
    CONSTRAINT uk_permissions_code UNIQUE (permission_code),
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id) REFERENCES modules_master (id)
);

CREATE TABLE role_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    hospital_id   BIGINT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_role_permissions UNIQUE (role_id, permission_id, hospital_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id),
    CONSTRAINT fk_role_permissions_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id)
);

CREATE INDEX idx_role_permissions_role ON role_permissions (role_id);

-- Portals are the UI shells a person can enter (staff console, doctor portal,
-- patient portal). Group membership decides which modules that portal exposes.
CREATE TABLE user_groups (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code  VARCHAR(50)  NOT NULL,
    group_name  VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_user_groups_code UNIQUE (group_code)
);

CREATE TABLE user_group_portal_access (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_group_id INTEGER NOT NULL,
    module_id     INTEGER NOT NULL,
    can_access    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_portal_access UNIQUE (user_group_id, module_id),
    CONSTRAINT fk_portal_access_group FOREIGN KEY (user_group_id) REFERENCES user_groups (id),
    CONSTRAINT fk_portal_access_module FOREIGN KEY (module_id) REFERENCES modules_master (id)
);
