-- Inpatient wards and their beds (MedFlow "Inpatient & Wards" module, tenant-scoped).

CREATE TABLE wards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    ward_type   VARCHAR(40),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_wards_name UNIQUE (hospital_id, name),
    CONSTRAINT fk_wards_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id)
);

CREATE TABLE beds (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT      NOT NULL,
    ward_id     BIGINT      NOT NULL,
    bed_number  INTEGER     NOT NULL,
    status      VARCHAR(20) NOT NULL,
    patient_id  BIGINT,
    occupied_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_beds_number UNIQUE (ward_id, bed_number),
    CONSTRAINT fk_beds_ward FOREIGN KEY (ward_id) REFERENCES wards (id),
    CONSTRAINT fk_beds_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT ck_beds_status CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE')),
    CONSTRAINT ck_beds_occupancy CHECK ((status = 'OCCUPIED') = (patient_id IS NOT NULL))
);

CREATE INDEX idx_beds_hospital ON beds (hospital_id);
-- A patient can lie in at most one bed at a time.
CREATE UNIQUE INDEX uk_beds_patient ON beds (patient_id);
