-- =====================================================================================
-- Staff / portal accounts. Every account belongs to exactly one hospital and carries a
-- role (what it may do) plus an optional user group (which portal it lands in).
--
-- Deviations from the reference design, both deliberate:
--   * email is globally unique — sign-in is by email alone, with no tenant selector in
--     the UI, so an address must resolve to exactly one account.
--   * reset_token / reset_token_expires_at support the "forgot password" flow.
-- =====================================================================================

CREATE TABLE users (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id            BIGINT       NOT NULL,
    user_uid               VARCHAR(36)  NOT NULL,
    role_id                INTEGER      NOT NULL,
    user_group_id          INTEGER,
    first_name             VARCHAR(100) NOT NULL,
    last_name              VARCHAR(100),
    email                  VARCHAR(120) NOT NULL,
    phone                  VARCHAR(20),
    password_hash          VARCHAR(255) NOT NULL,
    gender                 VARCHAR(10),
    date_of_birth          DATE,
    profile_photo_url      VARCHAR(255),
    status                 VARCHAR(30)  NOT NULL DEFAULT 'active',
    last_login_at          TIMESTAMP WITH TIME ZONE,
    reset_token            VARCHAR(64),
    reset_token_expires_at TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    is_deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_users_uid UNIQUE (user_uid),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_group FOREIGN KEY (user_group_id) REFERENCES user_groups (id),
    CONSTRAINT ck_users_status CHECK (status IN ('active', 'inactive', 'suspended', 'pending_verification')),
    CONSTRAINT ck_users_gender CHECK (gender IS NULL OR gender IN ('male', 'female', 'other'))
);

CREATE INDEX idx_users_hospital ON users (hospital_id);
CREATE INDEX idx_users_role ON users (role_id);
CREATE INDEX idx_users_reset_token ON users (reset_token);
