-- Pharmacy inventory (MedFlow module, tenant-scoped).

CREATE TABLE medications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id    BIGINT       NOT NULL,
    name           VARCHAR(150) NOT NULL,
    category       VARCHAR(100) NOT NULL,
    unit_price     NUMERIC(10, 2) NOT NULL DEFAULT 0,
    stock_quantity INTEGER      NOT NULL DEFAULT 0,
    reorder_level  INTEGER      NOT NULL DEFAULT 0,
    expiry_date    DATE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_medications_name UNIQUE (hospital_id, name),
    CONSTRAINT fk_medications_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT ck_medications_stock CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_medications_hospital ON medications (hospital_id);
