-- AI assistant transcript, one row per turn, scoped to a user's conversation thread.

CREATE TABLE chat_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id     BIGINT        NOT NULL,
    user_id         BIGINT        NOT NULL,
    conversation_id VARCHAR(36)   NOT NULL,
    role            VARCHAR(20)   NOT NULL,
    content         VARCHAR(4000) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_chat_messages_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_chat_messages_role CHECK (role IN ('USER', 'ASSISTANT'))
);

CREATE INDEX idx_chat_messages_thread ON chat_messages (user_id, conversation_id, created_at);
