CREATE TABLE IF NOT EXISTS patient_registration_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL,
  starting_profile VARCHAR(20) NOT NULL,
  field_states_json VARCHAR(4000) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_patient_registration_profile_hospital UNIQUE (hospital_id),
  CONSTRAINT chk_patient_registration_profile_starting_profile CHECK (
    starting_profile IN ('BASIC', 'COMPREHENSIVE')
  )
);

CREATE INDEX IF NOT EXISTS idx_patient_registration_profiles_hospital_id
  ON patient_registration_profiles (hospital_id);
