-- =====================================================================================
-- Patient hospitalisation tracking. A patient created (or later admitted) as inpatient
-- gets a hospitalisation_records row; daily_analyses hang off that stay and form the
-- vitals trend a doctor reviews. Discharging only flips status/discharge_date — history
-- is never deleted, matching how patients themselves are archived rather than removed.
-- =====================================================================================

ALTER TABLE patients ADD COLUMN IF NOT EXISTS is_hospitalised BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS hospitalisation_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id         BIGINT      NOT NULL,
    patient_id          BIGINT      NOT NULL,
    admission_date      TIMESTAMP WITH TIME ZONE NOT NULL,
    discharge_date      TIMESTAMP WITH TIME ZONE,
    ward                VARCHAR(50),
    bed                 VARCHAR(20),
    admitting_doctor_id BIGINT      NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'admitted',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_hospitalisation_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_hospitalisation_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_hospitalisation_doctor FOREIGN KEY (admitting_doctor_id) REFERENCES doctors (id),
    -- Persisted lower-case by HospitalisationStatusConverter, matching status/relation columns
    -- elsewhere in this module (see AccountStatusConverter, MappingRelationConverter).
    CONSTRAINT ck_hospitalisation_status CHECK (status IN ('admitted', 'discharged'))
);

CREATE INDEX IF NOT EXISTS idx_hospitalisation_patient ON hospitalisation_records (patient_id);
CREATE INDEX IF NOT EXISTS idx_hospitalisation_hospital_status ON hospitalisation_records (hospital_id, status);

CREATE TABLE IF NOT EXISTS daily_analyses (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospitalisation_record_id BIGINT      NOT NULL,
    patient_id                BIGINT      NOT NULL,
    blood_pressure            VARCHAR(20),
    pulse                     INT,
    temperature               NUMERIC(4, 1),
    spo2                      INT,
    notes                     VARCHAR(2000),
    recorded_by_doctor_id     BIGINT      NOT NULL,
    recorded_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_daily_analyses_record FOREIGN KEY (hospitalisation_record_id) REFERENCES hospitalisation_records (id),
    CONSTRAINT fk_daily_analyses_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_daily_analyses_doctor FOREIGN KEY (recorded_by_doctor_id) REFERENCES doctors (id)
);

CREATE INDEX IF NOT EXISTS idx_daily_analyses_record ON daily_analyses (hospitalisation_record_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_daily_analyses_patient ON daily_analyses (patient_id, recorded_at);
