ALTER TABLE patients ADD COLUMN phone VARCHAR(20);
ALTER TABLE patients ADD COLUMN blood_group VARCHAR(5);
ALTER TABLE patients ADD COLUMN address VARCHAR(255);
ALTER TABLE patients ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE patients ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
