-- =====================================================================================
-- Patient master data plus the two clinical record tables that hang off it, and the
-- mapping that lets a portal account (self, parent, guardian, …) act for a patient.
-- Patients are archived (status / is_deleted), never physically removed.
-- =====================================================================================

CREATE TABLE patients (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT,
    hospital_id             BIGINT       NOT NULL,
    patient_code            VARCHAR(30)  NOT NULL,
    first_name              VARCHAR(100) NOT NULL,
    last_name               VARCHAR(100),
    gender                  VARCHAR(10),
    date_of_birth           DATE,
    blood_group             VARCHAR(5),
    phone                   VARCHAR(20),
    email                   VARCHAR(120),
    address                 VARCHAR(1000),
    emergency_contact_name  VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    status                  VARCHAR(30)  NOT NULL DEFAULT 'active',
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    is_deleted              BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_patients_code UNIQUE (hospital_id, patient_code),
    CONSTRAINT uk_patients_email UNIQUE (hospital_id, email),
    CONSTRAINT fk_patients_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_patients_status CHECK (status IN ('active', 'inactive', 'suspended', 'pending_verification')),
    CONSTRAINT ck_patients_gender CHECK (gender IS NULL OR gender IN ('male', 'female', 'other'))
);

CREATE INDEX idx_patients_hospital ON patients (hospital_id);
CREATE INDEX idx_patients_name ON patients (last_name, first_name);

CREATE TABLE patient_medical_history (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id             BIGINT       NOT NULL,
    condition_name         VARCHAR(200) NOT NULL,
    notes                  VARCHAR(2000),
    recorded_by_doctor_id  BIGINT,
    recorded_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_history_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_history_doctor FOREIGN KEY (recorded_by_doctor_id) REFERENCES doctors (id)
);

CREATE INDEX idx_history_patient ON patient_medical_history (patient_id);

CREATE TABLE patient_reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          BIGINT       NOT NULL,
    hospital_id         BIGINT       NOT NULL,
    report_type         VARCHAR(100) NOT NULL,
    file_url            VARCHAR(255) NOT NULL,
    uploaded_by_user_id BIGINT,
    uploaded_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reports_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_reports_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_reports_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_reports_patient ON patient_reports (patient_id);

CREATE TABLE user_patient_mapping (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,
    patient_id         BIGINT      NOT NULL,
    relation           VARCHAR(20) NOT NULL DEFAULT 'self',
    is_primary_contact BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_patient UNIQUE (user_id, patient_id),
    CONSTRAINT fk_user_patient_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_patient_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT ck_user_patient_relation CHECK (relation IN ('self', 'parent', 'guardian', 'spouse', 'child', 'caretaker', 'other'))
);
