-- Workspace alert feed. Rows are produced by module events (bookings, schedule clashes,
-- lab results, low stock) and read by the UI's notification centre.

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT       NOT NULL,
    category    VARCHAR(20)  NOT NULL,
    severity    VARCHAR(20)  NOT NULL,
    title       VARCHAR(150) NOT NULL,
    message     VARCHAR(500) NOT NULL,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notifications_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT ck_notifications_category CHECK (category IN ('APPOINTMENT', 'LABORATORY', 'PHARMACY', 'SYSTEM')),
    CONSTRAINT ck_notifications_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

CREATE INDEX idx_notifications_feed ON notifications (hospital_id, created_at);
CREATE INDEX idx_notifications_read ON notifications (hospital_id, is_read);
