-- =====================================================================================
-- Clinical staff. A doctor is the professional profile attached to a user account:
-- names, contact details and login live on users, credentials and fees live here.
-- =====================================================================================

CREATE TABLE doctors (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT,
    hospital_id           BIGINT       NOT NULL,
    doctor_code           VARCHAR(30)  NOT NULL,
    specialty             VARCHAR(100) NOT NULL,
    qualification         VARCHAR(200),
    registration_number   VARCHAR(100) NOT NULL,
    years_of_experience   INTEGER      NOT NULL DEFAULT 0,
    consultation_fee      NUMERIC(10, 2) NOT NULL DEFAULT 0,
    digital_signature_url VARCHAR(255),
    bio                   VARCHAR(2000),
    status                VARCHAR(30)  NOT NULL DEFAULT 'active',
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_doctors_code UNIQUE (hospital_id, doctor_code),
    CONSTRAINT uk_doctors_registration UNIQUE (registration_number),
    CONSTRAINT uk_doctors_user UNIQUE (user_id),
    CONSTRAINT fk_doctors_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id),
    CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_doctors_status CHECK (status IN ('active', 'inactive', 'suspended', 'pending_verification'))
);

CREATE INDEX idx_doctors_hospital ON doctors (hospital_id);
CREATE INDEX idx_doctors_specialty ON doctors (specialty);

-- Recurring weekly slots (day_of_week 0=Sunday … 6=Saturday) or a one-off override for
-- a specific_date — exactly one of the two is set on any given row.
CREATE TABLE doctor_availability (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id             BIGINT  NOT NULL,
    day_of_week           INTEGER,
    specific_date         DATE,
    start_time            TIME    NOT NULL,
    end_time              TIME    NOT NULL,
    slot_duration_minutes INTEGER NOT NULL DEFAULT 30,
    is_available          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_availability_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT ck_availability_day CHECK (day_of_week IS NULL OR (day_of_week BETWEEN 0 AND 6)),
    CONSTRAINT ck_availability_scope CHECK (day_of_week IS NOT NULL OR specific_date IS NOT NULL)
);

CREATE INDEX idx_availability_doctor ON doctor_availability (doctor_id);

-- Which staff members (front desk, nurses, assistants) are attached to which doctor.
CREATE TABLE user_doctor_mapping (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    doctor_id     BIGINT      NOT NULL,
    hospital_id   BIGINT      NOT NULL,
    relation_type VARCHAR(50) NOT NULL DEFAULT 'assistant',
    is_primary    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_doctor UNIQUE (user_id, doctor_id),
    CONSTRAINT fk_user_doctor_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_doctor_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id),
    CONSTRAINT fk_user_doctor_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals (id)
);
